[build]
builder = "nixpacks"
buildCommand = "pnpm install && PORT=3000 BASE_PATH=/ pnpm --filter @workspace/shuttle run build && pnpm --filter @workspace/api-server run build"

[deploy]
startCommand = "node --enable-source-maps artifacts/api-server/dist/index.mjs"
restartPolicyType = "on_failure"
